// Calendar formatting provided below generated by Claude

const today = new Date();
const events = [];
let viewYear  = today.getFullYear();
let viewMonth = today.getMonth(); // 0-indexed

const monthNames = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
];

function renderCalendar() {
    const grid = document.getElementById('calendar-grid');
    const labels = grid.querySelectorAll('.day-label');
    grid.innerHTML = '';
    labels.forEach(l => grid.appendChild(l));

    document.getElementById('month-label').textContent =
        `${monthNames[viewMonth]} ${viewYear}`;

    const firstDay = new Date(viewYear, viewMonth, 1).getDay(); // 0=Sun
    const daysInMonth = new Date(viewYear, viewMonth + 1, 0).getDate();

    for (let i = 0; i < firstDay; i++) {
        const blank = document.createElement('div');
        blank.className = 'day-cell empty';
        grid.appendChild(blank);
    }

    for (let d = 1; d <= daysInMonth; d++) {
        const cell = document.createElement('div');
        cell.className = 'day-cell';

        if (viewYear === today.getFullYear() &&
            viewMonth === today.getMonth() &&
            d === today.getDate()) {
            cell.classList.add('today');
        }

        const num = document.createElement('span');
        num.className = 'day-number';
        num.textContent = d;
        cell.appendChild(num);

        const dateString = `${viewYear}-${String(viewMonth + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;

        events.forEach(event => {
            if (event.date === dateString) {
                const eventItem = document.createElement('p');
                eventItem.className = 'calendar-event';
                eventItem.textContent = event.title;
                eventItem.title = event.notes || "No notes";
                
                cell.appendChild(eventItem);
            }
        }); 
        grid.appendChild(cell);
    }
}

document.getElementById('prev-month').addEventListener('click', () => {
    viewMonth--;
    if (viewMonth < 0) { viewMonth = 11; viewYear--; }
    renderCalendar();
});

document.getElementById('next-month').addEventListener('click', () => {
    viewMonth++;
    if (viewMonth > 11) { viewMonth = 0; viewYear++; }
    renderCalendar();
});

document.getElementById('event-form').addEventListener('submit', function(event) {
    event.preventDefault();

    const title = document.getElementById('event-title').value.trim();
    const date = document.getElementById('event-date').value;
    const category = document.getElementById('event-category').value;
    const notes = document.getElementById('event-notes').value.trim();

    if (title === '') {
        alert('Please enter an event title.');
        return;
    }

    if (date === '') {
        alert('Please select a date.');
        return;
    }

    events.push({
        title: title,
        date: date,
        category: category,
        notes: notes
    });

    this.reset();
    renderCalendar();
});

renderCalendar();